# This is a basic workflow to help you get started with Actions
name: fake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - run: ls
