# This is a basic workflow to help you get started with Actions
name: snomed-publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ["self-hosted", "service"]
    container:
      image: docker:latest
    steps:
      - run: ls -halt /tmp
      - run: docker --version
