# This is a basic workflow to help you get started with Actions
name: fake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - env:
          FTR_GCP_BUCKET_SERVICE_ACCOUNT: ${{ secrets.FTR_GCP_BUCKET_SERVICE_ACCOUNT }}
        run: echo $FTR_GCP_BUCKET_SERVICE_ACCOUNT > ~/service-account.json
      - run: ls -halt ~/
      - run: gcloud auth activate-service-account --key-file=$HOME/service-account.json
      - run: touch /tmp/file-from-ci.test
      - run: gsutil cp /tmp/file-from-ci.test gs://ftr
