# This is a basic workflow to help you get started with Actions
name: fake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      
      - run: export SNOMED_GIT_REPO_PATH=$(pwd)

      - run: echo $SNOMED_GIT_REPO_PATH > test.json
      - run: cat test.json
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        
      - name: 'Build service-account.json'
        env:
          FTR_GCP_BUCKET_SERVICE_ACCOUNT: ${{ secrets.FTR_GCP_BUCKET_SERVICE_ACCOUNT }}
        run: echo $FTR_GCP_BUCKET_SERVICE_ACCOUNT > ~/service-account.json
        
      - name: 'Gcloud auth'
        run: gcloud auth activate-service-account --key-file=$HOME/service-account.json
        
      - name: 'Clone FTR repo'
        run: git clone --recurse-submodules https://github.com/HealthSamurai/ftr.git /tmp/ftr-git-repo
        
      - name: 'Spin up Postgres for Snomed build'
        run: cd /tmp/ftr-git-repo && make up && cd -
        
      
